apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: hello-world-akka-worker
  name: hello-world-akka-worker
spec:
  replicas: 3
  selector:
    app: hello-world-akka-worker
  template:
    metadata:
      labels:
        app: hello-world-akka-worker
    spec:
      containers:
      - name: hello-world-akka-worker
        image: hello-world-akka
        env:
        - name: JAVA_OPTIONS
          value: "-Dakka.cluster.seed-nodes.0=akka.tcp://ClusterSystem@hello-world-akka-seed-0.hello-world-akka-seed:2551 -Dakka.cluster.seed-nodes.1=akka.tcp://ClusterSystem@hello-world-akka-seed-1.hello-world-akka-seed:2551"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
