apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: cluster-listener-akka-worker
  name: cluster-listener-akka-worker
spec:
  replicas: 1
  selector:
    app: cluster-listener-akka-worker
  template:
    metadata:
      labels:
        app: cluster-listener-akka-worker
    spec:
      containers:
      - name: cluster-listener-akka-worker
        image: 172.30.1.1:5000/microservices/cluster-listener-akka:latest
        env:
        - name: JAVA_OPTIONS
          value: "-Dakka.cluster.seed-nodes.0=akka.tcp://ClusterSystem@cluster-listener-akka-seed-0.cluster-listener-akka-seed:2551 -Dakka.cluster.seed-nodes.1=akka.tcp://ClusterSystem@cluster-listener-akka-seed-1.cluster-listener-akka-seed:2551"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP

