apiVersion: v1
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: cluster-listener-akka
    name: cluster-listener-akka
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: cluster-listener-akka
    name: cluster-listener-akka
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: cluster-listener-akka:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/dsanchor/akka-openshift-cluster.git
      contextDir: cluster-listener
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: s2i-java:latest
          namespace: openshift
      type: Source
kind: List
metadata: {}

