apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    run: akka-worker2
  name: akka-worker2
spec:
  replicas: 3
  selector:
    run: akka-worker2
  template:
    metadata:
      labels:
        run: akka-worker2
    spec:
      containers:
      - name: akka-worker2
#        image: akka-cluster
        image: 172.30.1.1:5000/microservices/akka-cluster@sha256:b63cdc681658e54c844c3279f2aca1159bb74ddcf482e83ef45c165ac55384e5
        env:
        - name: SEED_NODES
          value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
