apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    run: akka-worker
  name: akka-worker
spec:
  replicas: 3
  selector:
    run: akka-worker
  template:
    metadata:
      labels:
        run: akka-worker
    spec:
      containers:
      - name: akka-worker
#        image: akka-cluster
        image: 172.30.1.1:5000/microservices/akka-cluster@sha256:b63cdc681658e54c844c3279f2aca1159bb74ddcf482e83ef45c165ac55384e5
        env:
        - name: SEED_NODES
          value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: akka-worker
  name: akka-worker
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    run: akka-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

