apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    run: akka-worker
  name: akka-worker
spec:
  replicas: 3
  selector:
    run: akka-worker
  template:
    metadata:
      labels:
        run: akka-worker
    spec:
      containers:
      - name: akka-worker
        image: akka-cluster-listener
        env:
        - name: JAVA_OPTIONS
          value: "-Dakka.cluster.seed-nodes.0=akka.tcp://ClusterSystem@akka-seed-0.akka-seed:2551 -Dakka.cluster.seed-nodes.1=akka.tcp://ClusterSystem@akka-seed-1.akka-seed:2551"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: akka-worker
  name: akka-worker
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    run: akka-worker
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

