apiVersion: v1
kind: Service
metadata:
  name: akka-seed
spec:
  ports:
  - port: 2551
    protocol: TCP
    targetPort: 2551
  selector:
    run: akka-seed
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    run: akka-seed
  name: akka-seed
spec:
  serviceName: akka-seed
  replicas: 2
  selector:
    matchLabels:
      run: akka-seed
  template:
    metadata:
      labels:
        run: akka-seed
    spec:
      containers:
      - name: akka-seed
#        image: akka-cluster
        image: 172.30.1.1:5000/microservices/akka-cluster@sha256:b63cdc681658e54c844c3279f2aca1159bb74ddcf482e83ef45c165ac55384e5
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOSTNAME_SUFFIX
          value: .akka-seed
#        - name: SEED_NODES
#          value: akka-seed-0.akka-seed,akka-seed-1.akka-seed
	 - name: JAVA_OPTIONS
          value: "-Dakka.cluster.seed-nodes.0=akka.tcp://ClusterSystem@akka-seed-0.akka-seed:2551 -Dakka.cluster.seed-nodes.1=akka.tcp://ClusterSystem@akka-seed-1.akka-seed:2551"
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP

