apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: remote-call-akka-worker
  name: remote-call-akka-worker
spec:
  replicas: 1
  selector:
    app: remote-call-akka-worker
  template:
    metadata:
      labels:
        app: remote-call-akka-worker
    spec:
      containers:
      - name: remote-call-akka-worker
        image: 172.30.1.1:5000/microservices/remote-call-akka:latest
        env:
        - name: JAVA_OPTIONS
          value: "-Dakka.cluster.seed-nodes.0=akka.tcp://RemoteGreetingSystem@remote-call-akka-seed-0.remote-call-akka-seed:2551 -Dakka.cluster.seed-nodes.1=akka.tcp://RemoteGreetingSystem@remote-call-akka-seed-1.remote-call-akka-seed:2551"
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: HOSTNAME_SUFFIX
          value: ""
        - name: JAVA_APP_JAR
          value: app.jar
        - name: AB_JOLOKIA_OFF
          value: ""
        - name: REMOTE_SERVICE_PATH
          value: "akka.tcp://HelloWorldSystem@hello-world-akka-seed-0.hello-world-akka-seed:2551/user/HelloWorld"
        livenessProbe:
          tcpSocket:
            port: 2551
        ports:
        - containerPort: 2551
          protocol: TCP
